# Generated by Django 4.2.17 on 2025-01-09 17:46

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.CharField(blank=True, max_length=58)),
                ("authorized", models.CharField(blank=True, max_length=52)),
                ("votes", models.BigIntegerField(blank=True, default=0)),
                ("permission", models.BigIntegerField(blank=True, default=0)),
                (
                    "currency",
                    models.CharField(blank=True, default="ALGO", max_length=5),
                ),
                (
                    "user",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BundleName",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="", max_length=50)),
                ("addresses", models.CharField(default="", max_length=6380)),
                ("bundle", models.CharField(blank=True, default="", max_length=40)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "profile",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.profile",
                    ),
                ),
            ],
            options={
                "ordering": [django.db.models.functions.text.Lower("name")],
            },
        ),
        migrations.AddConstraint(
            model_name="bundlename",
            constraint=models.UniqueConstraint(
                models.F("profile"),
                django.db.models.functions.text.Lower("name"),
                name="unique_profile_name",
            ),
        ),
        migrations.AddConstraint(
            model_name="bundlename",
            constraint=models.UniqueConstraint(
                fields=("profile", "bundle"), name="unique_profile_bundle"
            ),
        ),
    ]
