---
- name: Reload gunicorn
  ansible.builtin.systemd:
    name: "gunicorn-{{ env_name }}"
    state: reloaded
  become: true
  listen: "Reload web server"

- name: Reload openresty
  ansible.builtin.systemd:
    name: openresty
    state: reloaded
  become: true
  listen: "Reload web server"

- name: Enable and restart permissionsupdater
  ansible.builtin.systemd:
    name: "permissionsupdater-{{ env_name }}"
    state: restarted
    daemon_reload: true
    enabled: true
  become: true
  listen: "Enable and restart permissionsupdater"

- name: Enable and restart permissiondappupdater
  ansible.builtin.systemd:
    name: "permissiondappupdater-{{ env_name }}"
    state: restarted
    daemon_reload: true
    enabled: true
  become: true
  when: manage_services | default(true) | bool
  listen: "Enable and restart permissiondappupdater"
