---
- name: Reload gunicorn
  ansible.builtin.systemd:
    name: "gunicorn-{{ env_name }}"
    state: reloaded
  become: true
  listen: "Reload web server"

- name: Reload nginx
  ansible.builtin.systemd:
    name: nginx
    state: reloaded
  become: true
  listen: "Reload web server"

- name: Enable and restart permissionsupdater
  ansible.builtin.systemd:
    name: "permissionsupdater-{{ env_name }}"
    state: restarted
    daemon_reload: true
    enabled: true
  become: true
  listen: "Enable and restart permissionsupdater"
