[pytest]
pythonpath =
    website
    website/permissiondapp/dapp
DJANGO_SETTINGS_MODULE = config.settings.development
python_files = tests.py test_*.py *_tests.py
junit_family=legacy
asyncio_mode=auto
asyncio_default_fixture_loop_scope=function
addopts =
    --import-mode=importlib
    --ignore-glob=website/permissiondapp
    --ignore-glob=website/widgets
    -p no:warnings
norecursedirs = thumbnails