# Generated by Django 5.1.7 on 2025-08-18 15:13

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="bundlename",
            name="unique_profile_name",
        ),
        migrations.AddField(
            model_name="bundlename",
            name="public",
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name="bundlename",
            index=models.Index(
                django.db.models.functions.text.Lower("name"), name="idx_lower_name"
            ),
        ),
        migrations.AddIndex(
            model_name="bundlename",
            index=models.Index(
                django.db.models.functions.text.Lower("name"),
                models.F("public"),
                name="idx_lower_name_public",
            ),
        ),
        migrations.AddConstraint(
            model_name="bundlename",
            constraint=models.UniqueConstraint(
                models.F("profile"),
                django.db.models.functions.text.Lower("name"),
                condition=models.Q(("public", False)),
                name="unique_private_profile_name",
            ),
        ),
        migrations.AddConstraint(
            model_name="bundlename",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name"),
                condition=models.Q(("public", True)),
                name="unique_public_name",
            ),
        ),
    ]
