# Generated by Django 5.2.15 on 2026-09-14 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_profile_preferred_layout"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="live_refresh",
            field=models.BooleanField(default=False),
        ),
    ]
