# Generated by Django 5.2.15 on 2026-09-16 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_live_refresh"),
    ]

    operations = [
        migrations.CreateModel(
            name="LiveAllowanceBucket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(db_index=True, max_length=64, unique=True)),
                ("balance", models.FloatField(default=0.0)),
                ("capacity", models.FloatField(default=0.0)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("key",),
            },
        ),
    ]
