# Generated by Django 5.2.15 on 2026-09-20 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_live_allowance_bucket"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="api_tokens_valid_from",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
