# Generated by Django 5.2.15 on 2026-06-16 13:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0003_profile_auth_method_etc"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WalletLoginNonce",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.CharField(db_index=True, max_length=58)),
                ("nonce", models.CharField(max_length=64, unique=True)),
                ("chain", models.CharField(default="algorand", max_length=16)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("used", models.BooleanField(default=False)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["address", "used"],
                        name="walletauth__address_d1f041_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="walletauth__created_f335eb_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="LinkedAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.CharField(max_length=58)),
                ("canonical_address", models.CharField(db_index=True, max_length=58)),
                ("chain", models.CharField(max_length=20)),
                ("auth_method", models.CharField(max_length=20)),
                ("authorized", models.CharField(blank=True, default="", max_length=64)),
                ("is_primary", models.BooleanField(default=False)),
                ("login_enabled", models.BooleanField(default=False)),
                ("label", models.CharField(blank=True, default="", max_length=64)),
                (
                    "verified_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="linked_addresses",
                        to="core.profile",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("canonical_address",),
                        name="uniq_linkedaddress_canonical",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("is_primary", True)),
                        fields=("profile",),
                        name="uniq_linkedaddress_one_primary",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("is_primary", False),
                            ("login_enabled", True),
                            _connector="OR",
                        ),
                        name="ck_linkedaddress_primary_login",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="WalletNonce",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.CharField(db_index=True, max_length=58)),
                ("nonce", models.CharField(max_length=64, unique=True)),
                ("chain", models.CharField(default="algorand", max_length=16)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("used", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wallet_nonces",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["address", "used"],
                        name="walletauth__address_7b9c3b_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="walletauth__created_02374b_idx"
                    ),
                ],
            },
        ),
    ]
