---
- name: Import Redis installing tasks
  ansible.builtin.import_tasks: install.yml

- name: Import Redis tuning tasks
  ansible.builtin.import_tasks: tuning.yml

- name: Import web cache (second instance) tasks
  ansible.builtin.import_tasks: web_cache.yml
