"""Testing module for ``build-typefaces.py``.

The generator is a script, not an importable module, so it is loaded by path
and its module-level locations are pointed at a temporary tree. Nothing it
writes lands in the repository.
"""

import importlib.util
import json
import pathlib

import pytest

SCRIPT = pathlib.Path(__file__).parents[2] / "build-typefaces.py"


@pytest.fixture
def typefaces(tmp_path, monkeypatch):
    """The script with every path it reads or writes under `tmp_path`."""
    spec = importlib.util.spec_from_file_location("build_typefaces", SCRIPT)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)

    root = tmp_path / "site"
    (root / "static" / "fonts").mkdir(parents=True)
    (root / "static" / "css").mkdir(parents=True)
    monkeypatch.setattr(module, "HERE", root)
    monkeypatch.setattr(module, "FONT_DIR", root / "static" / "fonts")
    monkeypatch.setattr(module, "OUT", root / "static" / "css" / "typefaces.css")
    monkeypatch.setattr(module, "ANALYSIS", [tmp_path / "analysis.css"])
    module.root = root
    return module


def _font(module, name):
    (module.root / "static" / "fonts" / name).write_bytes(b"")


class TestBuildTypefacesHelpers:
    """Testing class for the functions that read the font tree and the themes."""

    def test_build_typefaces_slugify_lowers_and_dashes(self, typefaces):
        assert typefaces.slugify("Dancing Script") == "dancing-script"
        assert typefaces.slugify("  --Oswald!! ") == "oswald"

    def test_build_typefaces_font_files_keeps_only_gwfh_names(self, typefaces):
        _font(typefaces, "nunito-v32-latin-regular.woff2")
        _font(typefaces, "nunito-v32-latin-italic.woff2")
        _font(typefaces, "readme.woff2")
        _font(typefaces, "nunito-v32-latin-regular.ttf")

        found = typefaces.font_files()

        assert sorted(found) == ["nunito"]
        assert sorted(variant for variant, _ in found["nunito"]) == [
            "italic",
            "regular",
        ]

    def test_build_typefaces_pairings_reads_each_role_and_drops_fallbacks(
        self, typefaces, tmp_path
    ):
        (tmp_path / "analysis.css").write_text(
            '[data-theme="night"] { --font-display: "Fira Code", monospace;'
            " --font-sans: 'Inter', sans-serif; --font-mono: \"JetBrains Mono\"; }\n"
            '[data-theme="empty"] { color: red; }\n'
        )

        pairs = typefaces.pairings()

        assert pairs == {
            "night": {"display": "Fira Code", "sans": "Inter", "mono": "JetBrains Mono"}
        }

    def test_build_typefaces_pairings_without_a_source_file_is_empty(self, typefaces):
        assert typefaces.pairings() == {}

    def test_build_typefaces_shipped_themes_reads_quoted_and_bare_selectors(
        self, typefaces
    ):
        (typefaces.root / "static" / "css" / "style.tw.css").write_text(
            '[data-theme="asastats"]{}[data-theme=dark-blue]{}[data-theme="x"]{}'
        )

        assert typefaces.shipped_themes() == {"asastats", "dark-blue", "x"}


class TestBuildTypefacesMain:
    """Testing class for a full run of the generator over a small tree."""

    def _run(self, typefaces, tmp_path, capsys):
        (typefaces.root / "static" / "css" / "style.tw.css").write_text(
            '[data-theme="asastats"]{} [data-theme="asastats-dark"]{}'
            '[data-theme="night"]{}'
        )
        (tmp_path / "analysis.css").write_text(
            '[data-theme="night"] { --font-display: "Fira Code"; --font-sans: "Inter";'
            ' --font-mono: "JetBrains Mono"; }\n'
            '[data-theme="ghost"] { --font-display: "Ghost"; --font-sans: "Ghost"; }\n'
        )
        _font(typefaces, "oswald-v57-latin-regular.woff2")
        _font(typefaces, "oswald-v57-latin-italic.woff2")
        _font(typefaces, "nunito-v32-latin-regular.woff2")
        _font(typefaces, "fira-code-v1-latin-regular.woff2")
        _font(typefaces, "inter-v1-latin-variable.woff2")
        _font(typefaces, "jetbrains-mono-v1-latin-regular.woff2")
        typefaces.main()
        return capsys.readouterr().out

    def test_build_typefaces_main_writes_faces_and_both_pairing_blocks(
        self, typefaces, tmp_path, capsys
    ):
        self._run(typefaces, tmp_path, capsys)

        css = typefaces.OUT.read_text()
        assert css.startswith("/* GENERATED by build-typefaces.py")
        assert 'font-family: "Oswald";' in css
        assert 'src: url("../fonts/oswald-v57-latin-italic.woff2") format("woff2");' in css
        assert '[data-theme="night"] {' in css
        assert '  --typeface-mono: "JetBrains Mono";' in css
        assert '[data-typeface="night"] {' in css
        # `ghost` is in the analysis but not shipped, so it is not paired
        assert "ghost" not in css
        # the brand pair covers the shipped `asastats` theme with no analysis entry
        assert '[data-theme="asastats"] {' in css
        assert 'font-family: "Nunito";' in css

    def test_build_typefaces_main_skips_a_variable_face_and_reports_missing(
        self, typefaces, tmp_path, capsys
    ):
        out = self._run(typefaces, tmp_path, capsys)

        css = typefaces.OUT.read_text()
        # `variable` is not a numbered weight, so no @font-face is written for it
        assert "inter-v1-latin-variable" not in css
        assert "families on disk:" in out
        assert "MISSING from disk:" not in out

    def test_build_typefaces_main_reports_a_family_that_is_not_on_disk(
        self, typefaces, tmp_path, capsys
    ):
        (typefaces.root / "static" / "css" / "style.tw.css").write_text(
            '[data-theme="night"]{}'
        )
        (tmp_path / "analysis.css").write_text(
            '[data-theme="night"] { --font-display: "Absent Face"; --font-sans: "Inter"; }\n'
        )

        typefaces.main()

        out = capsys.readouterr().out
        assert "MISSING from disk:  ['Absent Face', 'Inter']" in out

    def test_build_typefaces_main_leaves_out_a_theme_without_a_display_or_body_face(
        self, typefaces, tmp_path, capsys
    ):
        (typefaces.root / "static" / "css" / "style.tw.css").write_text(
            '[data-theme="mono-only"]{}'
        )
        (tmp_path / "analysis.css").write_text(
            '[data-theme="mono-only"] { --font-mono: "JetBrains Mono"; }\n'
        )

        typefaces.main()

        css = typefaces.OUT.read_text()
        assert '[data-theme="mono-only"]' not in css
        assert '[data-typeface="mono-only"]' not in css

    def test_build_typefaces_main_writes_the_json_the_context_reads(
        self, typefaces, tmp_path, capsys
    ):
        self._run(typefaces, tmp_path, capsys)

        written = json.loads(
            (typefaces.root / "static" / "css" / "typefaces.json").read_text()
        )
        assert written["night"] == {
            "display": "Fira Code",
            "sans": "Inter",
            "mono": "JetBrains Mono",
        }
        assert written["asastats"] == {"display": "Oswald", "sans": "Nunito"}
