# Configuration for {{ site_name }}

include /etc/nginx/snippets/site_http_block.conf;

upstream channels-backend {
{% for i in range(daphne_numprocs | default(4) | int) %}
    server unix:{{ site_path }}/run/daphne{{ i }}.sock;
{% endfor %}
}


server {
    listen 80 default_server;
    server_name www.{{ site_name }} {{ site_name }} {{ inventory_hostname if is_molecule_test | default(false) else hostvars[inventory_hostname].ansible_host }};

    include /etc/nginx/snippets/site_server_block.conf;
}
