---
- name: Enable and restart web cache
  ansible.builtin.systemd:
    name: "redis_{{ redis_port }}.service"
    state: restarted
    enabled: true
    daemon_reload: true
  become: true
  listen: "Enable and restart web cache"
