"""
Django settings for the website project.

Generated by 'django-admin startproject' using Django 3.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

import sys
from datetime import timedelta
from pathlib import Path
from urllib.parse import quote

from dotenv import load_dotenv

from config import __version__
from utils.constants.apiv2 import SPECTACULAR_DESCRIPTION
from utils.helpers import get_env_variable

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
# permissiondapp is a submodule whose dapp/ modules import their siblings with bare
# names (e.g. `from config import ...`), expecting dapp/ to be the import root — the
# way the submodule runs under its own CI. Put dapp/ on sys.path so those imports
# resolve when website imports permissiondapp.dapp.*, without editing the submodule.
PERMISSIONDAPP_DAPP = BASE_DIR.parent / "permissiondapp" / "dapp"
if PERMISSIONDAPP_DAPP.is_dir() and str(PERMISSIONDAPP_DAPP) not in sys.path:
    sys.path.insert(0, str(PERMISSIONDAPP_DAPP))

DATABASE_HOST = get_env_variable("DATABASE_HOST", "localhost")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = get_env_variable("SECRET_KEY", "")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    "core.apps.CoreConfig",
    "widgets.apps.WidgetsConfig",
    "walletauth.apps.WalletauthConfig",
    "daphne",
    "template_partials",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sitemaps",
    "django.contrib.sites",
    "rest_framework",
    "corsheaders",
    "django_minify_html",
    "drf_spectacular",
    "drf_spectacular_sidecar",
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "allauth.socialaccount.providers.discord",
    "allauth.socialaccount.providers.github",
    "allauth.socialaccount.providers.google",
    "allauth.socialaccount.providers.reddit",
    "allauth.socialaccount.providers.twitter_oauth2",
    "captcha",
    "channels",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "core.middleware.CustomMinifyHtmlMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "allauth.account.middleware.AccountMiddleware",
    "core.middleware.CustomUserHeaderMiddleware",
    "core.middleware.DebugEnvMiddleware",
]

AUTHENTICATION_BACKENDS = [
    "allauth.account.auth_backends.AuthenticationBackend",
    "walletauth.backends.WalletAddressBackend",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            "templates",
            "website/templates",  # VS Code
        ],
        "OPTIONS": {
            "loaders": [
                (
                    "template_partials.loader.Loader",
                    [
                        "django.template.loaders.filesystem.Loader",
                        "django.template.loaders.app_directories.Loader",
                    ],
                )
            ],
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "core.context_processors.deployment_capabilities",
                "core.context_processors.global_constants",
                "core.context_processors.walletconnect",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"

# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": (
            "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"
        ),
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# allauth
# ACCOUNT_USERNAME_REQUIRED = True  # DEPRECATED
# ACCOUNT_EMAIL_REQUIRED = False  # DEPRECATED
ACCOUNT_SIGNUP_FIELDS = ["email", "username*", "password1*", "password2*"]
# ACCOUNT_AUTHENTICATION_METHOD = "username_email"  # DEPRECATED
ACCOUNT_LOGIN_METHODS = {"username", "email"}

ACCOUNT_EMAIL_VERIFICATION = "optional"
ACCOUNT_EMAIL_SUBJECT_PREFIX = ""
ACCOUNT_DEFAULT_HTTP_PROTOCOL = "http"
SOCIALACCOUNT_QUERY_EMAIL = True
LOGIN_REDIRECT_URL = "/home/"
ACCOUNT_LOGOUT_ON_GET = True
SOCIALACCOUNT_EMAIL_VERIFICATION = "none"
ACCOUNT_LOGIN_ON_EMAIL_CONFIRMATION = True
ACCOUNT_USER_DISPLAY = "utils.userhelpers.user_display"

# to override allauth forms use following parameters
# http://stackoverflow.com/a/25378883
ACCOUNT_SIGNUP_FORM_CLASS = "core.forms.CustomSignupForm"

SOCIALACCOUNT_PROVIDERS = {
    # https://discord.com/developers/applications
    "discord": {
        "APP": {
            "client_id": get_env_variable("DISCORD_APPLICATION_ID", ""),
            "secret": get_env_variable("DISCORD_SECRET", ""),
            "key": get_env_variable("DISCORD_PUBLIC_KEY", ""),
        }
    },
    # https://developer.x.com/en/portal/projects-and-apps
    "twitter_oauth2": {
        "APP": {
            "client_id": get_env_variable("TWITTER_CLIENT_ID", ""),
            "secret": get_env_variable("TWITTER_SECRET", ""),
            "key": "",
        }
    },
    # https://www.reddit.com/prefs/apps/
    "reddit": {
        "APP": {
            "client_id": get_env_variable("REDDIT_CLIENT_ID", ""),
            "secret": get_env_variable("REDDIT_SECRET", ""),
            "key": "",
        },
        "SCOPE": ["identity"],
        "USER_AGENT": "django:eIdhm4jSx-TM772A96uC7Q:1.0 (by /u/hopemeetme)",
    },
    # https://github.com/settings/developers
    "github": {
        "VERIFIED_EMAIL": True,
        "APP": {
            "client_id": get_env_variable("GITHUB_CLIENT_ID", ""),
            "secret": get_env_variable("GITHUB_SECRET", ""),
            "key": "",
        },
    },
    # https://console.developers.google.com/
    "google": {
        "APP": {
            "client_id": get_env_variable("GOOGLE_CLIENT_ID", ""),
            "secret": get_env_variable("GOOGLE_SECRET", ""),
            "key": "",
        },
        "SCOPE": [
            "profile",
            "email",
        ],
        "AUTH_PARAMS": {
            "access_type": "online",
        },
        "OAUTH_PKCE_ENABLED": True,
    },
}

COOKIE_ARGUMENTS = {}
SESSION_COOKIE_AGE = 2419200

# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = "/static/"
STATICFILES_DIRS = [
    BASE_DIR.parent / "static",
]
STATIC_ROOT = BASE_DIR.parent.parent.parent / "static"

DATA_PATH = BASE_DIR.parent.parent.parent / "data"

BASE_CDN_URL = "https://cdn.asastats.com"

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.dummy.DummyCache",
    }
}
CACHE_TTL = 60 * 90  # Cache time to live is 90 minutes.

SITE_ID = 1
SITEMAP_PROTOCOL = "http"

GOOGLE_OWNERSHIP_FILE = "google68d340e6b473efac.html"

REST_FRAMEWORK = {
    "DEFAULT_PARSER_CLASSES": [
        "rest_framework.parsers.JSONParser",
        "rest_framework_xml.parsers.XMLParser",
        "rest_framework_yaml.parsers.YAMLParser",
    ],
    "DEFAULT_RENDERER_CLASSES": [
        "rest_framework.renderers.JSONRenderer",
        "rest_framework_xml.renderers.XMLRenderer",
        "rest_framework_yaml.renderers.YAMLRenderer",
    ],
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTStatelessUserAuthentication",
    ),
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_THROTTLE_RATES": {
        "walletauth": "10/min",  # authorize (per user)
        "walletauth-login": "5/min",  # sign-in (per IP)
    },
}

# Website information
WEBSITE_NAME = get_env_variable("WEBSITE_NAME", "ASA Stats")
WEBSITE_SHORT_NAME = get_env_variable("WEBSITE_SLUG_NAME", "asastats")
WEBSITE_URL = get_env_variable("WEBSITE_URL", "https://www.asastats.com")
WEBSITE_DOMAIN = get_env_variable("WEBSITE_URL", "https://www.asastats.com")
WEBSITE_BASE_DOMAIN = get_env_variable("WEBSITE_BASE_DOMAIN", "asastats.com")
X_HANDLE = get_env_variable("X_HANDLE", "@asastatscom")
SUBREDDIT_NAME = get_env_variable("SUBREDDIT_NAME", "asastats")
ANDROID_APP = get_env_variable("ANDROID_APP", "com.asastats.app")
IOS_APP = get_env_variable("ANDROID_APP", "asa-stats-mobile/id6443547246")
MEDIUM_NAME = get_env_variable("MEDIUM_NAME", "@asastats")
DISCORD_INVITE = get_env_variable("DISCORD_INVITE", "Vjx7w7pAC7")
GITHUB_ORGANIZATION = get_env_variable("GITHUB_ORGANIZATION", "asastats")

# --- Rotated secrets ---
SIMPLE_JWT_KEY = get_env_variable("SIMPLE_JWT_KEY", "")

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(days=365),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=730),
    "ROTATE_REFRESH_TOKENS": True,
    "SIGNING_KEY": SIMPLE_JWT_KEY,
}

SPECTACULAR_SETTINGS = {
    "TITLE": "ASA Stats API",
    "DESCRIPTION": SPECTACULAR_DESCRIPTION,
    "VERSION": __version__,
    "OAS_VERSION": "3.1.0",
    "SWAGGER_UI_SETTINGS": {"persistAuthorization": True},
    # "SERVERS": [
    #     {"url": f"{WEBSITE_URL}/api/v2", "description": "Main server"},
    #     {"url": "http://127.0.0.1:8000/api/v2", "description": "Development server"},
    # ],
    "PREPROCESSING_HOOKS": [
        "api.helpers.preprocessing_filter_spec",
        "walletauth.schema.exclude_wallet_endpoints",
    ],
    "GET_LIB_DOC_EXCLUDES": "api.helpers.get_lib_doc_excludes",
    "SWAGGER_UI_DIST": "SIDECAR",  # shorthand to use the sidecar instead
    "SWAGGER_UI_FAVICON_HREF": STATIC_URL + "favicon-32x32.png",
    "REDOC_DIST": "SIDECAR",
}

# --- ASA Stats backend ---
ASASTATS_API_URL = get_env_variable("ASASTATS_API_URL", "https://api.asastats.com")
ASASTATS_API_KEY = get_env_variable("ASASTATS_API_KEY", "")
ASASTATS_API_TIMEOUT = int(get_env_variable("ASASTATS_API_TIMEOUT", 30))

# --- Algorand (public/private) ---
ALGOD_URL = get_env_variable("ALGOD_URL", "https://mainnet-api.algonode.cloud")
ALGOD_TOKEN = get_env_variable("ALGOD_TOKEN", "")
INDEXER_URL = get_env_variable("INDEXER_URL", "https://mainnet-idx.algonode.cloud")
INDEXER_TOKEN = get_env_variable("INDEXER_TOKEN", "")

ALGORAND_NODE_PATH = "/var/lib/algorand/"

REDIS_HOST = "localhost"
REDIS_PORT = 6379
REDIS_DB = 0

REDIS_PRIMARY_HOST = get_env_variable("REDIS_PRIMARY_HOST", "localhost")
REDIS_PORT_LOCAL = int(get_env_variable("REDIS_PORT_LOCAL", "6380"))
REDIS_AUTH = get_env_variable("REDIS_AUTH", "")

CSRF_TRUSTED_ORIGINS = [f"https://*.{WEBSITE_BASE_DOMAIN}"]

# Channels
ASGI_APPLICATION = "config.asgi.application"

REDIS_PASSWORD_ESCAPED = quote(REDIS_AUTH, safe="")
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [
                f"redis://:{REDIS_PASSWORD_ESCAPED}@{REDIS_HOST}:{REDIS_PORT_LOCAL}/0"
            ],
        },
    },
}


# # WIDGETS
WIDGETS_API_TOKEN = get_env_variable("WIDGETS_API_TOKEN", "")

INHOUSE_WIDGETS = ["historic", "folks", "haystack", "swapcore"]
THIRDPARTY_WIDGETS = []

STATICFILES_DIRS += [
    BASE_DIR.parent / "widgets" / "inhouse" / w / "static"
    for w in INHOUSE_WIDGETS
    if (BASE_DIR.parent / "widgets" / "inhouse" / w / "static").is_dir()
]
TEMPLATES[0]["DIRS"] += [
    BASE_DIR.parent / "widgets" / "inhouse" / w / "templates"
    for w in INHOUSE_WIDGETS
    if (BASE_DIR.parent / "widgets" / "inhouse" / w / "templates").is_dir()
]

PERMISSION_PROVIDER = "core.permission_providers.permissiondapp.PermissionDappProvider"

WALLET_TEST_MODE = False  # default; set True only in the functional-test settings

WALLET_CONNECT_PROJECT_ID = get_env_variable("WALLET_CONNECT_PROJECT_ID", "")

FOLKS_REFERRER_ADDRESS = get_env_variable("FOLKS_REFERRER_ADDRESS", "")

HAYSTACK_API_KEY = get_env_variable("HAYSTACK_API_KEY", "")
HAYSTACK_REFERRER_ADDRESS = get_env_variable("HAYSTACK_REFERRER_ADDRESS", "")
