#!/usr/bin/env python
"""Generate static/css/typefaces.css from the theme font pairings.

Two things are emitted:

* an ``@font-face`` for every weight of every family present in static/fonts.
  They are declared once, in one stylesheet, and cost only their own bytes:
  a browser downloads a font file when rendered text actually matches it, so
  a reader fetches the pair their theme uses and nothing else;
* a ``--typeface-display`` / ``--typeface-body`` pair per theme, plus the same
  pairs again under ``[data-typeface="<name>"]`` so a reader can override the
  theme's default with any other theme's pairing.

Single family names only, never a stack. Lightning CSS collapses a multi-family
value inside a custom property to its last entry, silently -- so the fallback
chain lives at the use site in input.css, where it survives minification.

Run after adding or removing fonts:

    python build-typefaces.py
"""

import json
import pathlib
import re
from collections import defaultdict

HERE = pathlib.Path(__file__).parent
FONT_DIR = HERE / "static" / "fonts"
OUT = HERE / "static" / "css" / "typefaces.css"
ANALYSIS = [
    pathlib.Path("/home/ipaleka/claude/theme-fonts/daisyui-theme-fonts.css"),
    pathlib.Path("/home/ipaleka/claude/theme-fonts/daisyui-custom-theme-fonts.css"),
]

#: gwfh writes `<slug>-v<N>-<subsets>-<variant>.woff2`.
FILENAME = re.compile(r"^(?P<slug>.+)-v\d+-(?P<subsets>[\w_]+)-(?P<variant>\w+)\.woff2$")

#: The brand pair, which is not a DaisyUI theme and so has no entry upstream.
BRAND = {"display": "Oswald", "sans": "Nunito"}

#: gwfh variant name -> the CSS weight and style it stands for.
WEIGHTS = {"regular": ("400", "normal"), "italic": ("400", "italic")}


def slugify(name):
    return re.sub(r"[^a-z0-9]+", "-", name.lower()).strip("-")


def font_files():
    """Return {slug: [(variant, filename), ...]} for everything on disk."""
    found = defaultdict(list)
    for path in sorted(FONT_DIR.glob("*.woff2")):
        match = FILENAME.match(path.name)
        if match:
            found[match.group("slug")].append((match.group("variant"), path.name))
    return found


def pairings():
    """Return {theme: {display, sans, mono}} from the analysis stylesheets."""
    out = {}
    for source in ANALYSIS:
        if not source.is_file():
            continue
        text = source.read_text()
        for block in re.finditer(r'\[data-theme="([\w-]+)"\]\s*\{([^}]*)\}', text):
            theme, body = block.group(1), block.group(2)
            roles = {}
            for role, value in re.findall(
                r"--font-(display|sans|mono):\s*([^;]+);", body
            ):
                roles[role] = value.split(",")[0].strip().strip("\"'")
            if roles:
                out[theme] = roles
    return out


def shipped_themes():
    """Return every theme registered in the compiled stylesheet."""
    css = (HERE / "static" / "css" / "style.tw.css").read_text()
    return {
        m.group(1) or m.group(2)
        for m in re.finditer(r'\[data-theme=(?:"([^"]+)"|([\w-]+))\]', css)
    }


def main():
    files = font_files()
    pairs = pairings()
    themes = shipped_themes()
    pairs.setdefault("asastats", BRAND)
    pairs.setdefault("asastats-dark", BRAND)
    pairs = {k: v for k, v in pairs.items() if k in themes}

    wanted = {
        family
        for roles in pairs.values()
        for family in roles.values()
    }
    missing = sorted(f for f in wanted if slugify(f) not in files)

    lines = [
        "/* GENERATED by build-typefaces.py -- do not edit.",
        "",
        "   Self-hosted faces and the per-theme pairings that use them. Rerun the",
        "   generator after adding or removing anything in static/fonts.",
        "",
        "   Families are named singly, never as a stack: Lightning CSS collapses a",
        "   multi-family value inside a custom property to its last entry. The",
        "   fallback chain lives at the use site in input.css instead. */",
        "",
    ]

    used_slugs = sorted({slugify(f) for f in wanted if slugify(f) in files})
    for slug in used_slugs:
        family = next(f for f in wanted if slugify(f) == slug)
        for variant, filename in sorted(files[slug]):
            weight, style = WEIGHTS.get(variant, (variant, "normal"))
            if not weight.isdigit():
                continue
            lines += [
                "@font-face {",
                f'  font-family: "{family}";',
                f"  font-style: {style};",
                f"  font-weight: {weight};",
                "  font-display: swap;",
                f'  src: url("../fonts/{filename}") format("woff2");',
                "}",
            ]

    lines += ["", "/* Each theme's own pairing, applied unless a reader overrides it. */"]
    for theme in sorted(pairs):
        roles = pairs[theme]
        display, body = roles.get("display"), roles.get("sans")
        if not (display and body):
            continue
        lines += [
            f'[data-theme="{theme}"] {{',
            f'  --typeface-display: "{display}";',
            f'  --typeface-body: "{body}";',
        ]
        if roles.get("mono"):
            lines.append(f'  --typeface-mono: "{roles["mono"]}";')
        lines.append("}")

    lines += [
        "",
        "/* A reader's override. Same values, keyed by the pairing's name rather",
        "   than the theme's, and written after the theme blocks so it wins on",
        "   source order -- both are single attribute selectors on <html>, so",
        "   specificity alone would not decide it. */",
    ]
    for theme in sorted(pairs):
        roles = pairs[theme]
        display, body = roles.get("display"), roles.get("sans")
        if not (display and body):
            continue
        lines += [
            f'[data-typeface="{theme}"] {{',
            f'  --typeface-display: "{display}";',
            f'  --typeface-body: "{body}";',
        ]
        if roles.get("mono"):
            lines.append(f'  --typeface-mono: "{roles["mono"]}";')
        lines.append("}")

    OUT.write_text("\n".join(lines) + "\n")

    print(f"families on disk:   {len(files)}")
    print(f"families used:      {len(used_slugs)}")
    print(f"themes paired:      {len(pairs)} of {len(themes)}")
    if missing:
        print(f"MISSING from disk:  {missing}")
    print(f"wrote {OUT.relative_to(HERE)} ({OUT.stat().st_size:,} bytes)")

    json.dump(
        {t: pairs[t] for t in sorted(pairs)},
        (HERE / "static" / "css" / "typefaces.json").open("w"),
        indent=1,
    )


if __name__ == "__main__":
    main()
