# Generated by Django 5.2.15 on 2026-06-16 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("walletauth", "0004_backfill_primary_linked_addresses"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="walletloginnonce",
            new_name="walletauth__address_d1f041_idx",
            old_name="walletauth_w_address_login_idx",
        ),
        migrations.RenameIndex(
            model_name="walletloginnonce",
            new_name="walletauth__created_f335eb_idx",
            old_name="walletauth_w_created_login_idx",
        ),
        migrations.RenameIndex(
            model_name="walletnonce",
            new_name="walletauth__address_7b9c3b_idx",
            old_name="walletauth_address_used_idx",
        ),
        migrations.RenameIndex(
            model_name="walletnonce",
            new_name="walletauth__created_02374b_idx",
            old_name="walletauth_created_idx",
        ),
    ]
